### ISSUE TITLE
Markbot is stuck bleeping and blooping

### ISSUE THREAD

**Issue by jen-power** [jen-power/kraken-good-accessibility#1]
<img width="799" alt="markbot-stuck" src="https://user-images.githubusercontent.com/43247074/69176449-ba685b80-0ad3-11ea-8faa-1b477af7f9fd.png">

@charlie-quinn

Markbot won't finish processing this assignment, but I'm not sure what it's getting stuck on.

**Comment by charlie-quinn** [comment]
This grade has been manually put in. 🤖 ✅
